services:
  postgres:
    image: postgres:16
    container_name: university-sms-postgres
    environment:
      POSTGRES_DB: university_sms
      POSTGRES_USER: university
      POSTGRES_PASSWORD: university
    ports:
      - "5440:5432"
    volumes:
      - university_sms_data:/var/lib/postgresql/data

volumes:
  university_sms_data:
